### ISSUE TITLE
[Robin] README.md 업데이트 요청

### ISSUE THREAD

**Issue by napi** [Sizzzz/cnu-team18-custom#4]
README.md 에 프로젝트 설명
그리고 Local 에서 빌드하고 테스트 하는 방법 업데이트 부탁드립니다.

수고하세요~

**Comment by napi** [comment]
Offline 에서 미리 이야기가 된 내용이 아니라면, Issues 나 Review 를 Close 하기 전에 Comment 를 남기는게 팀원이나 협업하는 동료개발자에 대한 배려입니다.
다음부턴 Close 하기 전에 간단한 코멘트를 부탁드립니다.

특별히 할 말이 없다면 👍 나 😭  같은 간단한 이모티콘 하나 남겨도 됩니다.

**Comment by Sizzzz** [comment]
죄송합니다😭
README 파일에 프로젝트 설명 반영하겠습니다!
